# Generated by Django 4.0.4 on 2022-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.CharField(blank=True, choices=[('Еда', 'Еда'), ('Места', 'Места')], max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('image', models.URLField(blank=True, verbose_name='Избражение')),
                ('link', models.CharField(max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Где поесть или куда сходить',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
