# Generated by Django 4.1.2 on 2023-01-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exort', '0002_usercardrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_card', to=settings.AUTH_USER_MODEL),
        ),
    ]
