# Generated by Django 4.1.2 on 2023-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exort', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
