# Generated by Django 4.1.2 on 2023-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exort', '0005_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='coo',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True, verbose_name='Price'),
        ),
    ]
