# Generated by Django 4.1.2 on 2023-01-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exort', '0007_alter_cards_coo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='coo',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Price'),
        ),
    ]
