# Generated by Django 4.1.2 on 2023-02-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exort', '0010_alter_rating_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='movie',
        ),
    ]
