# Generated by Django 4.2a1 on 2023-02-06 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exort', '0011_rename_post_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
