# Generated by Django 4.2a1 on 2023-02-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exort', '0014_blogpost_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
