# Generated by Django 4.2a1 on 2023-02-06 10:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exort', '0015_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='coo',
        ),
        migrations.AlterField(
            model_name='cards',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_card', to=settings.AUTH_USER_MODEL),
        ),
    ]
